name: Lint

on: push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ^14.x

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          path: "**/node_modules"

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint
